Changed LD_LIBRARY_PATH for albumentations lib
It was throwing the following errors:

ImportError: /nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/n7rw45lry3cmrpvk4y2qvbz

ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

After installing albumentations